---
apiVersion: v1
kind: Pod
metadata:
       name: singlepod-with-service
       namespace: mailadmin
       labels:
            app: edureka-pyapp
            env: prod
spec:
   containers:
            - name: pyapp
              image: lerndevops/samplepyapp:v1
              ports:
                  - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
       name: pyapp-svc
       namespace: mailadmin
       labels:
            app: pyapp-versioning
            env: prod
spec:
   selector:
          env: prod
   type: ClusterIP
   ports: 
       - port: 3000
         protocol: TCP
