---
apiVersion: v1
kind: Pod
metadata:
       name: pyapp-pod
       namespace: mailadmin
       labels:
            app: pyapp
            env: prod
spec:
   nodeName: worker1.jana.com
   containers:
            - name: pyaapp-c1
              image: lerndevops/samplepyapp:v1
              ports:
                  - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
       name: pyapp-svc
       namespace: mailadmin
spec:
   selector:
          app: pyapp
          env: prod
   type: NodePort
   ports:
       - port: 3000
         nodePort: 30003
