---
apiVersion: apps/v1
kind: Deployment
metadata:
       name: pyapp-deploy
       namespace: mailadmin
       labels:
            app: pyapp
            env: prod
spec:
   replicas: 3
   minReadySeconds: 10
   selector:
          matchExpressions:
                         - {key: env, operator: In, values: [qa,prod,sit]}
   strategy:
          type: RollingUpdate
          rollingUpdate:
                      maxUnavailable: 0
                      maxSurge: 2
   template:
          metadata:
                 name: pyapp-pod
                 namespace: mailadmin
                 labels:
                      app: pyapp
                      env: prod
          spec:
             nodeSelector:
                        app: webserver
                        env: prod
             containers:
                      - name: pyapp-c1
                        image: lerndevops/samplepyapp:v1
                        ports:
                            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
       name: pyapp-svc
       namespace: mailadmin
       labels:
            app: pyapp-svc1
            env: prod
spec:
   selector:
          app: pyapp
          env: prod
   type: ClusterIP
   ports:
       - port: 3000
         protocol: TCP
