---
apiVersion: v1
kind: Pod
metadata:
       name: pyapp-pod
       namespace: mailadmin
       labels:
            app: pyapp
            env: production
spec:
   nodeSelector:
              location: westus
              site: dr-primary
   containers:
            - name: pyapp-c1
              image: lerndevops/samplepyapp:v1
              ports:
                  - containerPort: 3000
