---
apiVersion: apps/v1
kind: Deployment
metadata:
       name: pyapp-deploy
       namespace: mailadmin
       labels:
            app: pyapp-deployv2
            env: prod
spec:
   replicas: 3
   selector:
          matchExpressions:
                         - {key: env, operator: In, values: [qa,prod,sit]}
   strategy:
          type: RollingUpdate
          rollingUpdate:
               maxUnavailable: 0 #if there are 3 replicas when there is new pod(surge pod 2)is created it removes 2 old pods by maintain 3replicas
               maxSurge: 2
   minReadySeconds: 30
   template:
          metadata:
                 name: pyapp-pod
                 namespace: mailadmin
                 labels:
                      env: prod
                      app: pyappv2
          spec:
             containers:
                      - name: pyapp-c1
                        image: lerndevops/samplepyapp:v2
                        ports:
                            - containerPort: 3000
             nodeName: worker1.jana.com
---
apiVersion: v1
kind: Service
metadata:
       name: pyapp-svc
       namespace: mailadmin
spec:
   selector:
          env: prod
          app: pyappv2
   type: ClusterIP
   ports:
       - port: 3000
         protocol: TCP
          
    
     
          
