---
apiVersion: apps/v1
kind: Deployment
metadata:
       name: webserver-deploy
       namespace: mailadmin
       labels:
            app: webserver
            env: prod
spec:
   replicas: 3
   strategy:
          type: RollingUpdate
          rollingUpdate:
                      maxUnavailable: 0
                      maxSurge: 2
   minReadySeconds: 10
   selector:
          matchExpressions:
                         - {key: env, operator: In, values: [qa,prod,sit]}
   template:
          metadata:
                 name: http-pod
                 namespace: mailadmin
                 labels:
                      app: webserver
                      env: prod
          spec:
             containers:
                      - name: http-c1
                        image: httpd
                        ports:
                            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
       name: http-svc 
       namespace: mailadmin
       labels:
            app: http-svc
            env: prod
spec:
   selector:
          app: webserver
          env: prod
   type: NodePort
   ports:
       - port: 80
         nodePort: 3080
        
                
