---
apiVersion: v1
kind: Pod
metadata:
       name: pyapp-pod
       namespace: mailadmin
       labels:
            app: pyapp
            env: prod
spec:
   nodeName: worker2.jana.com
   containers:
            - name: pyapp-c1
              image: lerndevops/samplepyapp:v1
              ports:
                  - containerPort: 3000
