---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
       name: pyapp-rs
       namespace: mailadmin
       labels:
            app: pyapp-rs
spec:
   replicas: 3
   selector:
          matchExpressions:
                         - {key: app, operator: In, values: [pyapp]}
   template:
          metadata:
                 name: pyapp-pod
                 namespace: mailadmin
                 labels:
                      app: pyapp
          spec:
             affinity:
                        podAntiAffinity:
                                      requiredDuringSchedulingIgnoredDuringExecution:
                                             - labelSelector:
                                                           matchExpressions:
                                                                   - {key: app, operator: In, values: [webserver]} 
                                                                   - {key: env, operator: In, values: [qa,prod,sit]}
                                               topologyKey: "kubernetes.io/hostname"
             containers:
                      - name: pyapp-c1
                        image: lerndevops/samplepyapp:v1
                        ports:
                            - containerPort: 3000
---
apiVersion: v1
kind: Service 
metadata:
       name: pyapp-svc
       namespace: mailadmin
spec:
   selector:
          app: pyapp
          env: prod
   type: ClusterIP
   ports:
       - port: 3000
         protocol: TCP
