---
apiVersion: v1
kind: Pod
metadata:
       name: nginx-init
       namespace: mailadmin
spec:
   initContainers:
                - name: nginx-init-c1
                  image: debian
                  command: ["/bin/sh", "-c", "echo ranjini > /usr/share/nginx/html/index.html", "sleep 30"]
#                  args:
#                     - echo ranjini > /usr/share/nginx/html/index.html
#                       sleep 30
                  volumeMounts:
                             - name: nginx-data
                               mountPath: /usr/share/nginx/html
   containers:
            - name: nginx
              image: nginx
              ports:
                  - containerPort: 80
              volumeMounts:
                         - name: nginx-data
                           mountPath: /usr/share/nginx/html
   volumes:
         - name: nginx-data
           emptyDir: {}

                        
                        
