---
apiVersion: v1
kind: Pod
metadata:
       name: nginxpod
       namespace: mailadmin
spec:
   containers:
            - name: nginx-c1
              image: nginx
              ports:
                  - containerPort: 80
 
