---
apiVersion: v1
kind: Namespace
metadata:
       name: mailadmin
---
apiVersion: v1
kind: Pod
metadata:
       name: httpd
       namespace: mailadmin
spec:
       containers:
               - name: httpd
                 image: httpd
                 ports:
                   -  containerPort: 80
             
