---
apiVersion: v1
kind: Pod
metadata:
       name: nginxsinglepod
       namespace: mailadmin
       labels:
            env: prod
spec:
   containers:
            - name: nginxc1
              image: nginx
              ports:
                  - containerPort: 80
